version: "2"

run:
  timeout: 5m
  tests: false # Skip test files to avoid errcheck issues

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocyclo

  settings:
    gocyclo:
      # Minimal code complexity to report.
      # Default: 30 (but we recommend 10-20)
      min-complexity: 15
